/**
 * POST /api/admin/reset-password
 * 管理员重置用户密码
 * 
 * 环境变量和配置要求：
 * 1. 在项目根目录创建 `.env.local` 文件
 * 2. 设置 `ADMIN_RESET_SECRET=你的密钥`（例如：ADMIN_RESET_SECRET=smartval-admin-dev-2026）
 * 3. 【必须】在设置或修改此环境变量后重启开发服务器 (npm run dev)
 * 
 * 安全机制：通过 x-admin-secret 请求头验证管理员身份
 * 环境变量 ADMIN_RESET_SECRET 必须设置，否则拒绝所有请求
 */

import { NextRequest, NextResponse } from 'next/server';
import crypto from 'crypto';
import { findUserByUsername, updateUserPassword } from '@/lib/auth/store';
import { hashPassword } from '@/lib/auth/password';
import { validatePassword } from '@/lib/auth/validators';

/** 生成随机临时密码（12位字母+数字） */
function generateTempPassword(length: number = 12): string {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    const bytes = crypto.randomBytes(length);
    let result = '';
    for (let i = 0; i < length; i++) {
        result += chars[bytes[i] % chars.length];
    }
    return result;
}

export async function POST(request: NextRequest) {
    try {
        // 检查环境变量是否配置
        const adminSecret = process.env.ADMIN_RESET_SECRET;
        if (!adminSecret) {
            console.warn('[admin-reset] ADMIN_RESET_SECRET 环境变量未设置，拒绝请求');
            return NextResponse.json(
                { error: '管理员重置功能未启用（ADMIN_RESET_SECRET 未配置）' },
                { status: 503 },
            );
        }

        // 验证管理员密钥
        const headerSecret = request.headers.get('x-admin-secret');
        if (!headerSecret || headerSecret !== adminSecret) {
            return NextResponse.json({ error: '管理员验证失败' }, { status: 401 });
        }

        const body = await request.json();
        const { username, newPassword } = body;

        // 验证用户名
        if (!username || typeof username !== 'string') {
            return NextResponse.json({ error: '请提供用户名' }, { status: 400 });
        }

        // 查找目标用户
        const user = findUserByUsername(username.trim().toLowerCase());
        if (!user) {
            return NextResponse.json({ error: `用户 "${username}" 不存在` }, { status: 404 });
        }

        // 确定新密码：手动指定 或 自动生成
        let finalPassword: string;
        let isAutoGenerated = false;

        if (newPassword && typeof newPassword === 'string' && newPassword.length > 0) {
            const pwResult = validatePassword(newPassword);
            if (!pwResult.valid) {
                return NextResponse.json({ error: pwResult.error }, { status: 400 });
            }
            finalPassword = newPassword;
        } else {
            finalPassword = generateTempPassword();
            isAutoGenerated = true;
        }

        // 哈希并更新
        const newHash = await hashPassword(finalPassword);
        const updated = updateUserPassword(user.id, newHash);
        if (!updated) {
            return NextResponse.json({ error: '密码重置失败' }, { status: 500 });
        }

        // 审计日志（不记录密码内容）
        console.log(
            `[admin-reset] 管理员操作：重置用户 "${user.username}" (${user.id}) 的密码` +
            ` | 模式: ${isAutoGenerated ? '自动生成' : '手动指定'}` +
            ` | 时间: ${new Date().toISOString()}`
        );

        // TODO: 未来替换为邮件发送重置链接
        return NextResponse.json({
            ok: true,
            username: user.username,
            message: `用户 "${user.username}" 的密码已重置`,
            ...(isAutoGenerated ? { tempPassword: finalPassword } : {}),
        });
    } catch (error) {
        console.error('[admin-reset] 错误:', error);
        return NextResponse.json({ error: '密码重置失败' }, { status: 500 });
    }
}
